# Generated by Django 4.2.3 on 2023-09-05 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commen', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catg_name', models.CharField(verbose_name=200)),
                ('discription', models.CharField(verbose_name=400)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commen.restaurant')),
            ],
        ),
    ]
