# Generated by Django 4.2.3 on 2023-09-08 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commen', '0002_admin'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=200)),
                ('food_type', models.CharField(verbose_name=200)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='restaurant/')),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commen.restaurant')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.category')),
            ],
        ),
    ]
