# Generated by Django 4.2.3 on 2023-09-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='item_name',
        ),
    ]
