# Generated by Django 4.2.3 on 2023-09-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_name_menu_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Restaurant',
            new_name='restaurant',
        ),
    ]
